{
 "title": "Cohere Monitoring",
 "tags": [ "openai-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "# ![openai](https://github.com/grafana/grafana-openai-monitoring/blob/main/assets/openai-logo-black.png?raw=true)"
   }
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total Requests made to OpenAI",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time(openai_promptTokens{job=~\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Request Duration",
   "type": "stat",
   "description": "Avg Duration taken by each request",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (openai_requestDuration{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Total Tokens",
   "type": "stat",
   "description": "Avg Total tokens used per request",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (openai_totalTokens{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Cost (USD)",
   "type": "stat",
   "description": "Average Cost over time in USD",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (openai_usageCost{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Completion Tokens",
   "type": "stat",
   "description": "Avg Total tokens used per request",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (openai_completionTokens{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Prompt Tokens",
   "type": "stat",
   "description": "Avg Total tokens used per request",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (openai_promptTokens{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Models",
   "type": "bargauge",
   "description": "Top 5 Models used in OpenAI API requests",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(model) (5, count_over_time(openai_completionTokens{job=~\"$job\"}[$__range]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Model usage overtime",
   "type": "timeseries",
   "description": "OpenAI Model usage overtime",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk by(model) (5, count_over_time(openai_completionTokens{job=~\"$job\"}[$__range]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Total Tokens",
   "type": "timeseries",
   "description": "Total Tokens used in each query overtime",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(job) (openai_totalTokens{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Usage by Model",
   "type": "timeseries",
   "description": "Token Usage by Model",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(model) (openai_totalTokens{job=~\"$job\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Duration overtime taken by each request",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openai_requestDuration{job=~\"$job\"}",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Completion Tokens",
   "type": "timeseries",
   "description": "Completion Tokens used overtime in each request",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(job) (openai_completionTokens{job=~\"$job\"})",
     "legendFormat": "Completition Tokens"
    }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "description": "Prompt Tokens used overtime in each request",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(job) (openai_promptTokens{job=~\"$job\"})",
     "legendFormat": "Prompt Tokens"
    }
   ]
  },
  {
   "title": "Prompts and Responses",
   "type": "table",
   "description": "Prompts and Responses",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "{job=~\"$job\"}"
    }
   ]
  }
 ]
}