[tool.poetry]
name = "o11y"
version = "0.1.0"
description = "Exporter for Grafana's AI Observability platform"
authors = ["Aaron Sanders <aaron.sanders@grafana.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
pydantic = "^2.7.0"
python-logging-loki = "^0.3.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
