apiVersion: 1

deleteDatasources:
  - name: Mimir

datasources:
  - name: MySQL
    type: mysql
    url: db:3306
    user: user
    secureJsonData:
      password: 'pass'
    jsonData:
      database: aitraining
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      timescaledb: false

  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      # The recommended scrape interval is 60s.
      timeInterval: '60s'

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: tid=(\w+)
          name: TraceID
          url: $${__value.raw}

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    orgId: 1
    url: http://pyroscope:4040/
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
