name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.4'

      - name: Check out code
        uses: actions/checkout@v4

      - name:  Image tag
        id: image-tag
        run: echo "version=$(./tools/image-tag)" >> $GITHUB_OUTPUT

      - name: Build and push to Docker Hub
        uses: grafana/shared-workflows/actions/push-to-gar-docker@main
        id: push-to-gar
        with:
          platforms: linux/amd64,linux/arm64
          file: ./ai-training-api/Dockerfile
          tags: |
            "${{ steps.image-tag.outputs.version }}"
            "latest"
          image_name: "ai-training-api"
          environment: "dev"